#!/bin/bash
CWD=$(cd $(dirname $0)/..; pwd)
cd $CWD


#MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET}
#DEB_SIGNING_PASSPHRASE=${DEB_SIGNING_PASSPHRASE}
#DEB_GPG_KEY_NAME=${DEB_GPG_KEY_NAME}
#RPM_SIGNING_PASSPHRASE=${RPM_SIGNING_PASSPHRASE}
#SIGN_PFX=${SIGN_PFX}
#SIGN_PFX_PW=${SIGN_PFX_PW}
#SIGN_WINDOWS=${SIGN_WINDOWS}
#WINDOWS_DDNPM_DRIVER=${WINDOWS_DDNPM_DRIVER}

set -x
SKIP_SIGN_MAC="${SKIP_SIGN_MAC:-false}" \
HARDENED_RUNTIME_MAC="${HARDENED_RUNTIME_MAC:-false}" \
OMNIBUS_BASE_DIR="${OMNIBUS_BASE_DIR:-/opt/omnibus}" \
OMNIBUS_GOMODCACHE="${OMNIBUS_GOMODCACHE:-${OMNIBUS_BASE_DIR}/gomod}" \
PY_RUNTIMES="3" \
make -C misc/omnibus
